docs: small fixes @ lpic2.201.2
lpic2book/src pull request #111
Opened 2023-07-10 20:30 UTC by kiraum

small fixes @ lpic2.201.2

2023-07-10 20:44 UTC, CoMPaTech requested changes
Approved aside from the URLs, please see #109 comment on relative URLs (if possible)

👍 great work

2023-07-10 21:10 UTC, kiraum commented
@CoMPaTech , I believe that like this should work as relative URL

2023-07-10 21:33 UTC, CoMPaTech commented
Let's check what #109 does :)

2023-07-11 05:07 UTC, CoMPaTech approved these changes

2023-07-11 05:07 UTC, merged